Update Hash-Cracker.py
Minor fixes:
   IOError: when 'SavedHashes' file doesn't exist (file is then created)
   IndexError: if Saved Hash is incorrectly formatted (skips to the next line in the file)